package model.request;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represent request body of create and update pet endpoints of PetStore API
 * Generated by POJO
 */
public class CreateOrUpdatePetRequestBody {

	@JsonProperty("photoUrls")
	private List<String> photoUrls;

	@JsonProperty("name")
	private String name;

	@JsonProperty("id")
	private int id;

	@JsonProperty("category")
	private Category category;

	@JsonProperty("tags")
	private List<TagsItem> tags;

	@JsonProperty("status")
	private String status;

	public void setPhotoUrls(List<String> photoUrls){
		this.photoUrls = photoUrls;
	}

	public void setName(String name){
		this.name = name;
	}

	public void setId(int id){
		this.id = id;
	}

	public void setCategory(Category category){
		this.category = category;
	}

	public void setTags(List<TagsItem> tags){
		this.tags = tags;
	}

	public void setStatus(String status){
		this.status = status;
	}

}